### ISSUE TITLE
Error first on setup

### ISSUE THREAD

**Issue by Keemtaker** [forsbergplustwo/partner-metrics#74] opened 2023-09-21 18:07 UTC
I cloned the app and tried to run it for the first time but I keep getting the error below after running `bin/setup`

> rails aborted!
> NoMethodError: undefined method `[]' for nil:NilClass
> /Users/keem/projects/partner-metrics/config/application.rb:36:in `<class:Application>'
> /Users/keem/projects/partner-metrics/config/application.rb:22:in `<module:PartnerMetrics>'
> /Users/keem/projects/partner-metrics/config/application.rb:21:in `<main>'
> /Users/keem/projects/partner-metrics/Rakefile:4:in `require_relative'
> /Users/keem/projects/partner-metrics/Rakefile:4:in `<main>'
> bin/rails:4:in `<main>'
> (See full trace by running task with --trace)
> 
> == Command ["bin/rails db:prepare"] failed ==

The error seems to point to the line below

`config.active_record.encryption.primary_key = Rails.application.credentials[:active_record_encryption][:primary_key]`

Any idea how I fix this ? Do I need to change the value in the credentials file ?

**Comment by forsbergplustwo** [comment] 2023-09-21 18:47
Thanks for letting me know @Keemtaker , I've updated the README with better first time setup instructions now: https://github.com/forsbergplustwo/partner-metrics#first-time-setup

Let me know if you get stuck on anything else, that we should add to README for others in the future.

**Comment by forsbergplustwo** [comment] 2023-09-22 11:39
Closing this, feel free to re-open with more details if you still have problems 😊

**Comment by architechpro** [comment] 2023-09-26 11:18
hi @forsbergplustwo 
We're getting the same error on step 3 of first time setup (`bin/rails credentials:edit`). Can you please suggest a solution or detalize the process a bit?

**Comment by forsbergplustwo** [comment] 2023-09-26 11:38
Hey @architechpro

I think the issue is it tries to boot the app to do the credentials:edit task, and it fails because credentials are not set yet. Can you try commenting out the lines related to encryption in `/config/application.rb`?

**Comment by forsbergplustwo** [comment] 2023-09-26 11:45
I'll try and create a better process for this, so we have a ready-made credentials file for dev and test in the repo .. which should avoid this 👍

**Comment by forsbergplustwo** [comment] 2023-09-26 14:42
If you pull latest from repo now, and follow the much shorter setup instructions it should be good to go 😎

**Closed** 2023-09-26 14:42 UTC

**Comment by architechpro** [comment] 2023-09-26 15:02
@forsbergplustwo that helped, thank you! 
However, after successfully launching `bin/dev`:

![Screenshot 2023-09-26 at 18 01 08](https://github.com/forsbergplustwo/partner-metrics/assets/65943221/8419b49c-58ab-4cba-9c96-836a840a79a8)

is there anything else we should do during first-time setup? Maybe assets build?

**Comment by forsbergplustwo** [comment] 2023-09-26 15:03
Try in your terminal: `yarn build --watch`

**Comment by architechpro** [comment] 2023-09-26 15:31
@forsbergplustwo thanks again, everything worked!
